events {}
http {
    include mime.types;
    server {
        listen 6767;  # Listen on 6767 directly
        server_name localhost;

        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }

        # Proxy API requests to the backend
        location /submit_request {
            proxy_pass http://192.168.10.100:6868;
        }
        location /get_requests {
            proxy_pass http://192.168.10.100:6868;
        }
        location /update_status {
            proxy_pass http://192.168.10.100:6868;
        }
        location /check_status {
            proxy_pass http://192.168.10.100:6868;
        }
        location /login {
            proxy_pass http://192.168.10.100:6868;
        }
        location /socket.io/ {
            proxy_pass http://192.168.10.100:6868;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
        }
    }
}
